Edge/Corner Case: A case where all compared values are the same (more than 2 values are compared in an if case in different if/elif statements)

In [ ]:
#this is xor, written with ^ (shift+6)
print(False^True)
print(False^False)
print(True^True)

True
False
False


In [ ]:
#string.isdigit()

print("0".isdigit())

True


In [ ]:
import numpy as np
print(np.zeros((2, 3)))
print(np.ones((3, 3)))
(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])