# NumPy

Today we'll introduce NumPy, an essential Python package for data science (and more generally for any kind of numerical computing). 

NumPy stands for *Num*erical *Py*thon and contains many features that are helpful when working with data. 

We'll demonstrate some of the most important features in the lecture. See the NumPy [documentation](https://numpy.org) for full package details.

## Importing NumPy

While we could just write `import numpy` this would require us to type out "numpy" before every function call from these modules.  Instead, it's conventional to rename these modules or their libraries to conventional abbreviations, resulting in less typing.  Thus:


In [1]:
import numpy as np

##  Lists vs NumPy arrays 

## Lists

Recall that a list is:

- a general purpose array
- untyped
- 1 dimension
- resizable 
- accessed with bracket [ ] notation and integer indices

### Arrays:

In contrast, a NumPy array is:

- intended to allow fast numerical calculations
- typed
- n-dimensions that are set when initialized
- fixed size that is set when initialized
- accessed with bracket [ ] notation and integer indices
- allows for broadcasting

## Creating 1D arrays

In [2]:
v = np.array([1, 2 ,3])
print(v)

[1 2 3]


## Creating 2D arrays

In [3]:
A = np.array([[1, 0, 0],
              [0 ,2, 0],
              [0, 0, 3]])  # 3x3 with 1,2,3 along the diagonal
print(A)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


## The shape of an array

It's very common to want to know the dimensions of an array of data - you may have just loaded the dataset without knowing how many rows of data are in it.  The shape *attribute* of an array (such as a matrix) is a *tuple* that tells you its dimensions.

In [4]:
print(A.shape)  # Tuples: like lists, but use () instead of [] 
print(v.shape)  # 1d outputs a comma to indicate it's still a tuple

(3, 3)
(3,)


## Operations with arrays

For arrays of the same dimension, we can add, subtract, multiply, and divide NumPy arrays of the same dimension. These default operators work element by element in the array.


In [5]:
v1 = v
print(v1)
v2 = np.array([4, 5, 6])
print(v2)
print("Adding 1D arrays: ",  v1 + v2)
print("Subtracting 1D arrays: ",  v1 - v2)
print("Multiplying 1D arrays: ", v1 * v2)
print("Dividing 1D arrays: ", v1 / v2)

[1 2 3]
[4 5 6]
Adding 1D arrays:  [5 7 9]
Subtracting 1D arrays:  [-3 -3 -3]
Multiplying 1D arrays:  [ 4 10 18]
Dividing 1D arrays:  [0.25 0.4  0.5 ]


### Broadcasting

The term [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) describes how NumPy treats arrays with different shapes during arithmetic operations. For example, when a number is added to a vector, it's added to all the elements of the vector. The same thing goes for multiplication, raising to a power, and some other mathematical operations - they're applied element by element to the whole array. We will look at this in-depth later in the lecture.

Broadcasting rules apply when performing these operations between arrays and numbers. Let's see this in practice.

In [6]:
print(v1)
print("Adding a constant: ", v1 + 2)
print("Subtracting a constant: ", v1 - 2)
print("Multiplying by a constant: ", v1 * 2)
print("Dividing by a constant: ", v1 / 2)

[1 2 3]
Adding a constant:  [3 4 5]
Subtracting a constant:  [-1  0  1]
Multiplying by a constant:  [2 4 6]
Dividing by a constant:  [0.5 1.  1.5]


## Common computations and axis

numpy offers a variety of fast methods for doing common computations - for example, finding the min of each column, or the mean of each row.  You can generally change whether these methods act on rows or columns by passing an argument "axis=0" (to produce a result for each column) or "axis=1" (to produce a value for each row).

In [7]:
my_array = np.array([[1,2,3], 
                     [4,5,6]])
print(np.min(my_array, axis=0))

[1 2 3]


In [8]:
print(np.mean(my_array, axis=1))

[2. 5.]


## Matrix-vector multiplication

NumPy also makes mathematically defined operations like matrix-vector multiplication easy. These operations are fundamental operations in statistics and machine learning. For instance, in neural networks, matrix-vector multiplication propagates information forward in the network. We do not have to fully understand matrix-vector multiplication if we are only learning how to program. However, if you continue as a data scientist, then it is essential to understand this operation.

Multiplying a matrix by a vector creates a new vector where each element in the new vector is a weighted sum of the elements in the original vector. 

What does this really mean?  Let's consider a $2 \times 2$ matrix $B$ defined as

$$
B = 
\begin{bmatrix}
3 & 2 \\
4 & -1
\end{bmatrix},
$$

and a $2 \times 1$ vector $w$ 

$$
w = 
\begin{bmatrix}
1 \\
-1 \\
\end{bmatrix}.
$$

Each row of the matrix provides the weights for a weighted sum of the vector elements, such that row *i* provides the weights used to calculate element *i* of the output:

$$
Bw =
\begin{pmatrix}
3 * 1 + 2 * -1 \\
4 * 1 + -1 * -1
\end{pmatrix}
= 
\begin{pmatrix}
1 \\
5
\end{pmatrix}.
$$

In numpy, matrix multiplication can be carried out just by using the @ operator.

In [9]:
B = np.array([[3, 2], 
              [4, -1]])
w = np.array([1, -1])
z = B @ w
print(z)

[1 5]


## Slicing

One very convenient thing that you can do with numpy arrays (which you can also do with lists and strings) is "slicing," or grabbing values between particular indices.  The syntax for a 1D array is my_array[first_included_index:first_excluded_index], so the second index isn't in the result.


In [10]:
my_array = np.array([8, 6, 7, 5, 3, 0, 9])
print(my_array[1:3]) # prints index 1 and 2, not 3

[6 7]


Leaving off the second number means all the rest of the indices will be included.  Leaving off the first means all elements before the index after the colon will be included.

In [11]:
print(my_array)
print(my_array[1:])

[8 6 7 5 3 0 9]
[6 7 5 3 0 9]


In [12]:
my_array[:3]

array([8, 6, 7])

This all works in a similar way for the 2D case.  Slicing 2D arrays is very common when dealing with datasets.  You may choose to be interested in only certain rows, representing certain datapoints, or certain columns, representing certain features.

One detail is that the ranges are comma-separated.  (You might be tempted to use double-square-brackets if you thought of them as list-of-lists.)

In [13]:
# Could suppose this is data where each row is an observation
# of latitude, longitude, and temperature
my_matrix = np.array([[42.3, 71.1, 92],
                      [40.7, 70.0, 85],
                      [47.6, 122.0, 82]])
print(my_matrix)
# Now we decide to drop the first datapoint
# and only care about latitude/longitude
two_by_two_square = my_matrix[1:, :2]
print(two_by_two_square)

[[ 42.3  71.1  92. ]
 [ 40.7  70.   85. ]
 [ 47.6 122.   82. ]]
[[ 40.7  70. ]
 [ 47.6 122. ]]


A colon alone refers to grabbing all rows or columns.

In [14]:
no_last_column = my_matrix[:, :2] # no temperature
print(no_last_column)

[[ 42.3  71.1]
 [ 40.7  70. ]
 [ 47.6 122. ]]


A final note about slicing:  it produces a *view* of the original data rather than copying the data into a new place.  This means **modifications to the slice will also modify the original data**.  Several other methods dealing with arrays, like reshape(), create views instead of copies, so check documentation if you're not sure whether you can safely modify their results.

In [15]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
print(a)
b = a[1:3]
print(b)
b[1] = 100 # modify the slice...
print(a) # ...and see the original change

[0 1 2 3 4 5]
[1 2]
[  0   1 100   3   4   5]


## Zero arrays

If your code is going to count things, it's common to want to create a matrix or vector that is zero to start, so that other values can be added to this.  The zeros() function handily creates arrays that are all zeros, of arbitrary size.

In [16]:
print(np.zeros(3)) #create an array of zeros with length 3
print(np.zeros((2, 3))) # create a 2x3 matrix of zeros

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
